version: 2.1
jobs:
  bygg:
    docker:
      - image: circleci/node:12.4.0-browsers

    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Installer avhengigheter
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Kjør enhetstester
          command: yarn test
      - run:
          name: Kjør ende-til-ende-tester
          command: yarn test:e2e
      - run:
          name: Bygg produksjonsversjon av React app
          command: yarn build
      - setup_remote_docker
      - run:
          name: Bygg Docker image
          command: docker build -t "navikt/kontakt-oss:$CIRCLE_SHA1" .
      - run:
          name: Push Docker image
          command: |
            echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
            docker push "navikt/kontakt-oss:$CIRCLE_SHA1"
            echo "Docker image: $CIRCLE_SHA1"

  deploy-til-dev:
    docker:
      - image: 'navikt/deployment-cli:v0.1.6'
    steps:
      - deploy:
          cluster: "dev-sbs"
          nais-yaml: "nais-dev-sbs.yaml"

  deploy-til-prod:
    docker:
      - image: 'navikt/deployment-cli:v0.1.6'
    steps:
      - deploy:
          cluster: "prod-sbs"
          nais-yaml: "nais-prod-sbs.yaml"

commands:
  deploy:
    description: Deploy til et gitt miljø
    parameters:
      cluster:
        type: string
      nais-yaml:
        type: string
    steps:
      - checkout
      - run:
          name: Deploy til << parameters.cluster >>
          command: deployment-cli deploy create --cluster=<< parameters.cluster >> --repository=navikt/kontakt-oss --team=teamtag --resource=<< parameters.nais-yaml >> --version=$CIRCLE_SHA1

workflows:
  version: 2.1
  bygg_og_deploy:
    jobs:
      - bygg
      - deploy-til-dev:
          requires:
            - bygg
          filters:
            branches:
              only:
                - master
      - godkjenn-til-prod:
          type: approval
          requires:
            - bygg
          filters:
            branches:
              only:
                - master
      - deploy-til-prod:
          requires:
            - godkjenn-til-prod
          filters:
            branches:
              only:
                - master
