version: 2
jobs:
  bygg-og-lag-dockerimage:
    docker:
    # TODO Det er en issue i Jest kombinert med node:8.15.1 som hindrer testene i å kjøre på CircleCI. https://github.com/facebook/create-react-app/issues/6591
    # TODO Det er fikset i Jest, CRA har ikke oppdatert versjonen. Midlertidig fix: Nedgrader Node i circleCI-bygget.
    - image: circleci/node:8.15.0

    steps:
    - checkout

    - restore_cache:
        name: Hent Yarn cache
        keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Installer avhengigheter
        command: |
          yarn install --frozen-lockfile
    - save_cache:
        name: Lagre Yarn cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
            - ~/.cache/yarn
    - run:
        name: Bygg produksjonsversjon av React app
        command: yarn build

    - setup_remote_docker
    - run:
        name: Sett miljøvariable
        command: |
          echo 'export RELEASE_VERSION="$(git rev-list --count $CIRCLE_SHA1)"' >> $BASH_ENV
          echo 'export BRANCH_PREFIX=`[ $CIRCLE_BRANCH == "master" ] && echo "" || echo $CIRCLE_BRANCH\_`' >> $BASH_ENV
          echo 'export DOCKER_IMAGE_VERSIONED="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$BRANCH_PREFIX$RELEASE_VERSION"' >> $BASH_ENV
          echo 'export DOCKER_IMAGE_UNVERSIONED="$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
    - run:
        name: Bygg Docker image
        command: docker build -t "$DOCKER_IMAGE_VERSIONED" -t "$DOCKER_IMAGE_UNVERSIONED" .
    - run:
        name: Push Docker image
        command: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push "$DOCKER_IMAGE_VERSIONED"
          docker push "$DOCKER_IMAGE_UNVERSIONED"

  enhetstester:
    docker:
      - image: circleci/node:8.15.0-browsers

    steps:
      - checkout
      - restore_cache:
          name: Hent Yarn cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Installer avhengigheter
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          name: Lagre Yarn cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Kjør enhetstester
          command: yarn test

  # TODO: Gjenbruk av installasjon av avhengigheter
  e2e-test:
    docker:
      - image: circleci/node:8.15.0-browsers

    steps:
    - checkout

    - restore_cache:
        name: Hent Yarn cache
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Installer avhengigheter
        command: |
          yarn install --frozen-lockfile
    - save_cache:
        name: Lagre Yarn cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn
    - run:
        name: Kjør ende-til-ende-tester
        command: yarn test:e2e

workflows:
  version: 2
  bygg_og_kjør_e2e_test:
    jobs:
      - bygg-og-lag-dockerimage
      - enhetstester
      - e2e-test
      - bygg-og-lag-dockerimage:
          requires:
            - bygg-og-lag-dockerimage
            - enhetstester
            - e2e-test
