apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: kontakt-oss
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  ingresses:
    - {{ingress}}
  liveness:
    path: /kontakt-oss/internal/isAlive
    initialDelay: 5
  readiness:
    path: /kontakt-oss/internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /kontakt-oss/internal/metrics
  env:
    - name: API_GATEWAY
      value: {{api_gateway}}
    - name: DECORATOR_EXTERNAL_URL
      value: {{decorator_external_url}}
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
  envFrom:
    - secret: kontakt-oss
  accessPolicy:
    outbound:
      external:
        - host: {{decorator_external_url}}
