apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: kontakt-oss
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: {{version}}
  team: arbeidsgiver
  port: 3000
  vault:
    enabled: true
  ingresses:
    - https://arbeidsgiver-q.nav.no/kontakt-oss
  liveness:
    path: /kontakt-oss/internal/isAlive
    initialDelay: 5
  readiness:
    path: /kontakt-oss/internal/isReady
    initialDelay: 5
  env:
    - name: API_GATEWAY
      value: https://api-gw-q0.oera.no
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: DECORATOR_EXTERNAL_URL
      value: https://www-q1.nav.no/dekoratoren/?context=arbeidsgiver
  prometheus:
    enabled: true
    path: /kontakt-oss/internal/metrics
